### ISSUE TITLE
등록하기 페이지 - 동물 특성 점수 부여 컴포넌트 제작

### ISSUE THREAD

**Issue by JeonDoGyun** [Step3-kakao-tech-campus/Team16_FE#31]
## Description
- Pet을 등록할 때 정해진 특성에 점수를 부여할 수 있다. 
- MBTI 검사에 나오는 예시처럼 버튼 UI를 통해 적절한 점수를 부여할 수 있다. 

## To-Do
- [x] 버튼 컴포넌트 스타일 지정
- [x] 버튼 액션을 통한 Pet 등록 state 변경 기능 구현
- [x] 컴포넌트의 스타일 지정
- [x] Figma 와이어프레임 변경

## Etc
- 피그마에 있는 화면 설계에서 변경된 부분이 있기 때문에 BE에 얘기하는 부분 필요
