### ISSUE TITLE
README.md 문서 작업

### ISSUE THREAD

**Issue by JeonDoGyun** [Step3-kakao-tech-campus/Team16_FE#32]
## Description
- FE 프로젝트 전반에 대한 `README.md` 문서 작업 필요

## To-DO
- [x] 프로젝트 아이템 로고, 팀명, 프로젝트 설명
- [x] FE 개발자 소개
- [x] 기술 스택 정리 (로고와 함께)
- [x] 요구사항 명세서 (BE - Wiki 공유)
- [x] 채택된 디렉토리 구조 + 디자인 패턴 소개
- [x] 구현할 페이지에 대한 와이어프레임 이미지(구현한 사람이 이미지 아래쪽에 기능 설명 넣기)
-> 구현 후 실제 웹 상 이미지로 변경하고, 설명 추가
