### ISSUE TITLE
등록하기 페이지 - 동물 세부정보 입력 컴포넌트 제작

### ISSUE THREAD

**Issue by LimSumi** [Step3-kakao-tech-campus/Team16_FE#33]
## Description
- 동물의 세부정보를 입력받을 수 있다.

## Todo
- [x] 세부정보 입력 컴포넌트 제작
  - [x] input 박스 컴포넌트 제작
  - [x] 라디오 버튼 컴포넌트 제작
  - [x] 드롭다운 컴포넌트 제작
  - [x] 등록하기 페이지에 컴포넌트 삽입
  - [x] 입력 상태관리 구현
